### ISSUE TITLE
sssd.conf services line broken

### ISSUE THREAD

**Issue by lkthomas** [joshuabaird/puppet-ipaclient#16]
when I manually execute command ipa-client-install, it will do auto discovery and do all the setup, then sssd.conf will be generated:

[sssd]
services = nss, pam, ssh, sudo

But when I use puppet to run ipa-client-install, sssd section become like this:

[sssd]
services =  , sudo

why is it missing nss, pam and ssh on services line?

**Comment by stbenjam** [comment]
Sounds like sssd services fact isn't getting loaded.

Do you get an answer for `facter --puppet sssd_services`? What OS? What version of FreeIPA?

**Comment by lkthomas** [comment]
facter --puppet sssd_services
, sudo

Ubuntu 14.04.1 LTS, running freeipa-client from offical repo version 3.3.4-0ubuntu3.1

**Comment by stbenjam** [comment]
This is fixed in ada9a73b4, and released as version 2.4.0.

On RHEL and Fedora, SSSD is already installed so it works fine, but on Ubuntu, SSSD isn't installed until ipa-client is, so there's no initial value of sssd_services.

I include a default value now if sssd isn't installed.  For the machines you already did, you'll need to fix /etc/sssd/sssd.conf manually.
